# Generated by Django 4.1.9 on 2023-06-03 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='roll_number',
            field=models.IntegerField(default=0),
        ),
    ]
