# Generated by Django 4.2 on 2023-05-26 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fee', '0002_feeinstallment_delete_feemonth'),
    ]

    operations = [
        migrations.AddField(
            model_name='fees',
            name='amount_paid',
            field=models.IntegerField(default=0),
        ),
    ]
