# Generated by Django 4.2 on 2023-05-26 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fee', '0004_alter_fees_installment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feeinstallment',
            name='installment',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
